name: Test
on:
  push:
    branches:
      - master

jobs:
  plugin_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: asdf_plugin_test
      uses: asdf-vm/actions/plugin-test@v1
      with:
        command: "gotestsum --version"
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
